### ISSUE TITLE
部分樣式需要修正

### ISSUE THREAD

**Issue by ChouChouHu** [leo5470/CodeYourStageExercise#1]
嗨 Leo！Pull 目前的 main 下來看之後
作業有兩個部分的樣式需要修正，主要有兩大區塊
1. 希望底色能統一呈白色
<img width="766" alt="image" src="https://github.com/leo5470/CodeYourStageExercise/assets/10724255/ccfec028-3ca4-41cf-acbf-f64619bc7b9e">
  
2. 同上，目前是透明底
<img width="1139" alt="image" src="https://github.com/leo5470/CodeYourStageExercise/assets/10724255/93e99fd0-e42f-49ab-9eac-222460fde4ee">

  
其他部分都沒有問題，請在 9/17 截止前修復並回覆在此 issue 就好囉
另外，表單部分都回得很好
唯有一題「這次的作業是屬於偏前端還是後端呢？」其實答案應是前端
開學前可再想想！

**Comment by leo5470** [comment]
您好，在剛剛已經commit了，再去看看
此外，偏前端的部分則是我忽略了是在修復「呼叫API」的部分，而不是修復API本身運作，所以應該偏前端才對

**Comment by ChouChouHu** [comment]
沒問題囉！
你很強，希望未來能多多 carry 其他同學
